# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Akvamarin' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'CommonKit', :git => 'https://github.com/idapgroup/CommonKit.git'
    pod 'DataKit', :git => 'https://github.com/idapgroup/DataKit.git'
    pod 'UIKit', :git => 'https://github.com/idapgroup/UIKit.git'
    pod 'ActiveRecordKit', :git => 'https://github.com/idapgroup/ActiveRecordKit.git'
    pod 'MBCalendarKit', '~>3.0.4'
  # Pods for Akvamarin

end
