# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Akvamarin' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'MBCalendarKit', '~>3.0.4'
    pod 'MagicalRecord'
    
  # Pods for Akvamarin

end
